name: "WhatWatt GO Integration"
description: "Easily integrate WhatWatt GO energy monitoring device with Home Assistant"
version: "1.0.0"
slug: "whatwatt_go"
init: false
arch:
  - armhf
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
hassio_api: true
homeassistant_api: true
options:
  whatwatt_ip: ""
  mqtt_broker: "core-mosquitto"
  mqtt_username: ""
  mqtt_password: ""
  mqtt_port: 1883
  mqtt_topic: "energy/whatwatt/go"
  reporting_interval: 30
  obis_codes:
    - "1_7_0"   # Power In
    - "2_7_0"   # Power Out
    - "1_8_0"   # Energy In
    - "2_8_0"   # Energy Out
    - "32_7_0"  # Voltage L1
    - "52_7_0"  # Voltage L2
    - "72_7_0"  # Voltage L3
schema:
  whatwatt_ip: str
  mqtt_broker: str
  mqtt_username: str
  mqtt_password: str
  mqtt_port: int
  mqtt_topic: str
  reporting_interval: int(10,300)
  obis_codes:
    - str